# Code refactoring
It's code review time!

Please have a look at this awful code and make it better.

It's an eye-sore.

The following code is super bad (intentionally, I promise).
There's lots of identation errors, duplicated / copied+pasted code, improper use of methods, bad naming of variables etc.

Just a mess.

You can analyse the dataset using `pandas` - but the actual code will not use `pandas` but `csv`.

In [1]:
import pandas as pd

df = pd.read_csv('./resources/factory_salary.csv')

df.head()

,Date,Profession,Rank,Equipment,Insalubrity,Size_Production,Salary
0,2009-01-01,Metal heater,7,Heating furnaces,22,580,26020.0
1,2009-01-01,Metal heater,6,Heating furnaces,22,580,22980.0
2,2009-01-01,Metal heater,5,Heating furnaces,22,580,20350.0
3,2009-01-01,Metal heater,5,Heating furnaces,22,580,20350.0
4,2009-01-01,Metal heater,4,Heating furnaces,22,580,18090.0

In [15]:
import csv

def finder(options = {}):
    with open("./resources/factory_salary.csv", "rt") as csvfile:
      data = csv.reader(csvfile, delimiter=',', quotechar='"')
      print(next(data))

In [39]:
options = {'Profession':'Metal heater'}
with open("./resources/factory_salary.csv", "rt") as csvfile:
      data = csv.reader(csvfile, delimiter=',', quotechar='"')
      some_list=next(data)
      result_list=[]
      print(some_list.index('Profession'))
      for k, v in options.items():
        for row in data:
            if row[some_list.index('Profession')] == v:
              result_list.append(row)

print(result_list)

1
[['2009-01-01', 'Metal heater', '7', 'Heating furnaces', '22', '580', '26020.0'], ['2009-01-01', 'Metal heater', '6', 'Heating furnaces', '22', '580', '22980.0'], ['2009-01-01', 'Metal heater', '5', 'Heating furnaces', '22', '580', '20350.0'], ['2009-01-01', 'Metal heater', '5', 'Heating furnaces', '22', '580', '20350.0'], ['2009-01-01', 'Metal heater', '4', 'Heating furnaces', '22', '580', '18090.0'], ['2009-02-01', 'Metal heater', '7', 'Heating furnaces', '22', '790', '26020.0'], ['2009-02-01', 'Metal heater', '6', 'Heating furnaces', '22', '790', '22980.0'], ['2009-02-01', 'Metal heater', '5', 'Heating furnaces', '22', '790', '20350.0'], ['2009-02-01', 'Metal heater', '5', 'Heating furnaces', '22', '790', '20350.0'], ['2009-02-01', 'Metal heater', '4', 'Heating furnaces', '22', '790', '18090.0'], ['2009-03-01', 'Metal heater', '7', 'Heating furnaces', '22', '820', '26020.0'], ['2009-03-01', 'Metal heater', '6', 'Heating furnaces', '22', '820', '22980.0'], ['2009-03-01', 'Metal heater', '5', 'Heating furnaces', '22', '820', '20350.0'], ['2009-03-01', 'Metal heater', '5', 'Heating furnaces', '22', '820', '20350.0'], ['2009-03-01', 'Metal heater', '4', 'Heating furnaces', '22', '820', '18090.0'], ['2009-04-01', 'Metal heater', '7', 'Heating furnaces', '22', '1200', '30561.764705882353'], ['2009-04-01', 'Metal heater', '6', 'Heating furnaces', '22', '1200', '26895.882352941175'], ['2009-04-01', 'Metal heater', '5', 'Heating furnaces', '22', '1200', '23724.41176470588'], ['2009-04-01', 'Metal heater', '5', 'Heating furnaces', '22', '1200', '23724.41176470588'], ['2009-04-01', 'Metal heater', '4', 'Heating furnaces', '22', '1200', '20999.117647058825'], ['2009-05-01', 'Metal heater', '7', 'Heating furnaces', '22', '1250', '31210.58823529412'], ['2009-05-01', 'Metal heater', '6', 'Heating furnaces', '22', '1250', '27455.29411764706'], ['2009-05-01', 'Metal heater', '5', 'Heating furnaces', '22', '1250', '24206.470588235294'], ['2009-05-01', 'Metal heater', '5', 'Heating furnaces', '22', '1250', '24206.470588235294'], ['2009-05-01', 'Metal heater', '4', 'Heating furnaces', '22', '1250', '21414.70588235294'], ['2009-06-01', 'Metal heater', '7', 'Heating furnaces', '22', '950', '27317.647058823528'], ['2009-06-01', 'Metal heater', '6', 'Heating furnaces', '22', '950', '24098.823529411766'], ['2009-06-01', 'Metal heater', '5', 'Heating furnaces', '22', '950', '21314.117647058825'], ['2009-06-01', 'Metal heater', '5', 'Heating furnaces', '22', '950', '21314.117647058825'], ['2009-06-01', 'Metal heater', '4', 'Heating furnaces', '22', '950', '18921.176470588238'], ['2009-07-01', 'Metal heater', '7', 'Heating furnaces', '22', '1400', '33157.05882352941'], ['2009-07-01', 'Metal heater', '6', 'Heating furnaces', '22', '1400', '29133.529411764706'], ['2009-07-01', 'Metal heater', '5', 'Heating furnaces', '22', '1400', '25652.64705882353'], ['2009-07-01', 'Metal heater', '5', 'Heating furnaces', '22', '1400', '25652.64705882353'], ['2009-07-01', 'Metal heater', '4', 'Heating furnaces', '22', '1400', '22661.470588235294'], ['2009-08-01', 'Metal heater', '7', 'Heating furnaces', '22', '1180', '30302.235294117647'], ['2009-08-01', 'Metal heater', '6', 'Heating furnaces', '22', '1180', '26672.117647058825'], ['2009-08-01', 'Metal heater', '5', 'Heating furnaces', '22', '1180', '23531.58823529412'], ['2009-08-01', 'Metal heater', '5', 'Heating furnaces', '22', '1180', '23531.58823529412'], ['2009-08-01', 'Metal heater', '4', 'Heating furnaces', '22', '1180', '20832.882352941175'], ['2009-09-01', 'Metal heater', '7', 'Heating furnaces', '22', '1080', '29004.58823529412'], ['2009-09-01', 'Metal heater', '6', 'Heating furnaces', '22', '1080', '25553.29411764706'], ['2009-09-01', 'Metal heater', '5', 'Heating furnaces', '22', '1080', '22567.470588235294'], ['2009-09-01', 'Metal heater', '5', 'Heating furnaces', '22', '1080', '22567.470588235294'], ['2009-09-01', 'Metal heater', '4', 'Heating furnaces', '22', '1080', '20001.70588235294'], ['2009-10-01', 'Metal heater', '7', 'Heating furnaces', '22', '780', '26020.0'], ['2009-10-01', 'Metal heater', '6', 'Heating furnaces', '22', '780', '22980.0'], ['2009-10-01', 'Metal heater', '5', 'Heating furnaces', '22', '780', '20350.0'], ['2009-10-01', 'Metal heater', '5', 'Heating furnaces', '22', '780', '20350.0'], ['2009-10-01', 'Metal heater', '4', 'Heating furnaces', '22', '780', '18090.0'], ['2009-11-01', 'Metal heater', '7', 'Heating furnaces', '22', '1020', '28226.0'], ['2009-11-01', 'Metal heater', '6', 'Heating furnaces', '22', '1020', '24882.0'], ['2009-11-01', 'Metal heater', '5', 'Heating furnaces', '22', '1020', '21989.0'], ['2009-11-01', 'Metal heater', '5', 'Heating furnaces', '22', '1020', '21989.0'], ['2009-11-01', 'Metal heater', '4', 'Heating furnaces', '22', '1020', '19503.0'], ['2009-12-01', 'Metal heater', '7', 'Heating furnaces', '22', '810', '26020.0'], ['2009-12-01', 'Metal heater', '6', 'Heating furnaces', '22', '810', '22980.0'], ['2009-12-01', 'Metal heater', '5', 'Heating furnaces', '22', '810', '20350.0'], ['2009-12-01', 'Metal heater', '5', 'Heating furnaces', '22', '810', '20350.0'], ['2009-12-01', 'Metal heater', '4', 'Heating furnaces', '22', '810', '18090.0']]

In [1]:
import csv

def finder(options = {}):
  with open("./resources/factory_salary.csv", "rt") as csvfile:
    data = csv.reader(csvfile, delimiter=',', quotechar='"')
     # skip header
    next(data)
    csv_data = []
    for row in data:
      csv_data.append(row)

    salary = []
    if 'Profession' in options:
      result = []
      for row in csv_data:
        if row[1] == options['Profession']:
          result.append(row)
      csv_data = result

    if 'Equipment' in options:
      result = []
      for row in csv_data:
        if row[3] == options['Equipment']:
          result.append(row)
      csv_data = result 

    if 'Size_Production' in options:
      result = []
      for row in csv_data:
        if row[5] == options['Size_Production']:
          result.append(row)
      csv_data = result

    if 'Date' in options:
      result = []
      for row in csv_data:
        if row[0] == options['Date']:
          result.append(row)
      csv_data = result

    output = []
    for row in csv_data:
      mapped = {}
      mapped['Date'] = row[0]
      mapped['Profession'] = row[1]
      mapped['Rank'] = row[2]
      mapped['Equipment'] = row[3]
      mapped['Insalubrity'] = row[4]
      mapped['Size_Production'] = row[5]
      mapped['Salary'] = row[6]
      output.append(mapped)

    return output


    def finder_by(options):
    with open("./resources/factory_salary.csv", "rt") as csvfile:
      data = csv.reader(csvfile, delimiter=',', quotechar='"')
      # skip header
      next(data)
      csv_data = []
      for row in data:
        csv_data.append(row)

    if 'Profession' in options:
      for row in csv_data:
        if row[1] == options['Profession']:
          mapped = {}
          mapped['Date'] = row[0]
          mapped['Profession'] = row[1]
          mapped['Rank'] = row[2]
          mapped['Equipment'] = row[3]
          mapped['Insalubrity'] = row[4]
          mapped['Size_Production'] = row[5]
          mapped['Salary'] = row[6]
          return mapped

    if 'Equipment' in options:
      for row in csv_data:
        if row[3] == options['Equipment']:
          mapped = {}
          mapped['Date'] = row[0]
          mapped['Profession'] = row[1]
          mapped['Rank'] = row[2]
          mapped['Equipment'] = row[3]
          mapped['Insalubrity'] = row[4]
          mapped['Size_Production'] = row[5]
          mapped['Salary'] = row[6]
          return mapped

    if 'Rank' in options:
      for row in csv_data:
        if row[2] == options['Rank']:
          mapped = {}
          mapped['Date'] = row[0]
          mapped['Profession'] = row[1]
          mapped['Rank'] = row[2]
          mapped['Equipment'] = row[3]
          mapped['Insalubrity'] = row[4]
          mapped['Size_Production'] = row[5]
          mapped['Salary'] = row[6]
          return mapped

    if 'Date' in options:
      for row in csv_data:
        if row[0] == options['Date']:
          mapped = {}
          mapped['Date'] = row[0]
          mapped['Profession'] = row[1]
          mapped['Rank'] = row[2]
          mapped['Equipment'] = row[3]
          mapped['Insalubrity'] = row[4]
          mapped['Size_Production'] = row[5]
          mapped['Salary'] = row[6]
          return mapped

    raise RecordNotFound

class RecordNotFound(Exception):
  pass

In [2]:
# test the code - this part is ok, don't worry - trust the QA Engineer

def test_finder_returns_events():
    assert len(finder({'Profession': 'Quality controller'})) == 12

def test_finder_returns_correct_keys():
    row = finder(
        {
            'Profession': 'Quality controller',
            'Date': '2009-11-01'
        }
    )
    keys = ['Date','Profession','Rank','Equipment','Insalubrity','Size_Production','Salary']
    values = ['2009-11-01','Quality controller','7','Control and measuring equipment','0','1020','24266.0']
    for i in range(0, len(keys)):
      assert row[0][keys[i]] == values[i]

def test_finder_returns_events_by_equipment():
    assert len(finder({'Equipment': 'Heating furnaces'})) == 84

def test_finder_returns_events_by_rank():
    assert len(finder({'Rank': '7'})) == 264

def test_finder_returns_no_events():
    assert len(finder({'Profession': 'Unemployed'})) == 0

def test_finder_by_event_by_equipment():
    row = finder_by({'Equipment': 'Heating furnaces'})
    keys = ['Date','Profession','Rank','Equipment','Insalubrity','Size_Production','Salary']
    values = ['2009-01-01','Metal heater','7','Heating furnaces','22','580','26020.0']
    for i in range(0, len(keys)):
      assert row[keys[i]] == values[i]

try:
    test_finder_returns_events()
    test_finder_returns_correct_keys()
    test_finder_returns_events_by_equipment()
    test_finder_returns_events_by_rank()
    test_finder_returns_no_events()
    test_finder_by_event_by_equipment()

    print('All tests passed!')
except Exception as e:
    print('FAILED')
    print(e.with_traceback)
    raise

All tests passed!